# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownForce < Formula
  desc "Evidence collection CLI application for phishing and illegal copyright infringement websites"
  homepage "https://github.com/canaria-computer/down-force"
  version "1.3.0"
  license "LicenseRef-PolyForm-Strict-1.0.0 OR LicenseRef-PolyForm-Internal-Use-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.3.0/down-force_1.3.0_darwin_amd64.tar.gz"
      sha256 "33065c3a5db6559ba48b1d1fc426dc548872dca4c7feb28ba5aba0e0a0ea8e8c"

      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.3.0/down-force_1.3.0_darwin_arm64.tar.gz"
      sha256 "60b9f61da84e9fe72d19b3ca462aab7b07fc51db0e55f7d6be9b6f2eafb24a4c"

      def install
        bin.install "down-force"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.3.0/down-force_1.3.0_linux_amd64.tar.gz"
      sha256 "75a47d97aab78bbf026141ba956e981e0912835d6d11ef33245cffa26a49e688"
      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.3.0/down-force_1.3.0_linux_arm64.tar.gz"
      sha256 "380e959eee3a6644ee12b6e13aa788bcf81bb270bb4b412f63a87c2e65a6f293"
      def install
        bin.install "down-force"
      end
    end
  end

  def caveats
    <<~EOS
      This software is dual-licensed under PolyForm Strict License 1.0.0 and PolyForm Internal Use License 1.0.0.
      See LICENSE files for details.
    EOS
  end
end
