# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownForce < Formula
  desc "Evidence collection CLI application for phishing and illegal copyright infringement websites"
  homepage "https://github.com/canaria-computer/down-force"
  version "1.2.1-dev1.0"
  license "LicenseRef-PolyForm-Strict-1.0.0 OR LicenseRef-PolyForm-Internal-Use-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.2.1-dev1.0/down-force_1.2.1-dev1.0_darwin_amd64.tar.gz"
      sha256 "b6563704a88f3fb401f2e5e235a13f9367ebdbc60d214e00e5e9e5197c39aea5"

      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.2.1-dev1.0/down-force_1.2.1-dev1.0_darwin_arm64.tar.gz"
      sha256 "8947af2ccf7b8f9ac8abb4c3735a8e12b38e1d7b26e506e3b408dff96f8410b1"

      def install
        bin.install "down-force"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.2.1-dev1.0/down-force_1.2.1-dev1.0_linux_amd64.tar.gz"
      sha256 "16fa6c2ed2ca1233cf9e23f7f605aa96b574228879393b3f7894087eff9509db"
      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v1.2.1-dev1.0/down-force_1.2.1-dev1.0_linux_arm64.tar.gz"
      sha256 "db34b787cac0eb7133386c99a974274e9fcb684cd42c8e2ea26e90ea30c24451"
      def install
        bin.install "down-force"
      end
    end
  end

  def caveats
    <<~EOS
      This software is dual-licensed under PolyForm Strict License 1.0.0 and PolyForm Internal Use License 1.0.0.
      See LICENSE files for details.
    EOS
  end
end
