# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DownForce < Formula
  desc "Evidence collection CLI application for phishing and illegal copyright infringement websites"
  homepage "https://github.com/canaria-computer/down-force"
  version "0.14.0-dev1.1"
  license "LicenseRef-PolyForm-Strict-1.0.0 OR LicenseRef-PolyForm-Internal-Use-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/canaria-computer/down-force/releases/download/v0.14.0-dev1.1/down-force_0.14.0-dev1.1_darwin_amd64.tar.gz"
      sha256 "ab65101230bd43d7a8054ea338dba0946ea1f363338c09e70561dae1835826c7"

      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/canaria-computer/down-force/releases/download/v0.14.0-dev1.1/down-force_0.14.0-dev1.1_darwin_arm64.tar.gz"
      sha256 "ca8646ae4a70fd11db1aa1ef466036a60e7607941f9cd6f9f78fe545e6544401"

      def install
        bin.install "down-force"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v0.14.0-dev1.1/down-force_0.14.0-dev1.1_linux_amd64.tar.gz"
      sha256 "17f6650e03df0bda17e16141b6d2eb5b8597a3659485e19c1903e07d6a3a33ce"
      def install
        bin.install "down-force"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canaria-computer/down-force/releases/download/v0.14.0-dev1.1/down-force_0.14.0-dev1.1_linux_arm64.tar.gz"
      sha256 "aea19887fbd180fa4d2153aca1dde780ea4865cb9755f1ca126b2b6e427a1a5e"
      def install
        bin.install "down-force"
      end
    end
  end

  def caveats
    <<~EOS
      This software is dual-licensed under PolyForm Strict License 1.0.0 and PolyForm Internal Use License 1.0.0.
      See LICENSE files for details.
    EOS
  end
end
